
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kubeos-node-template
  description: An example of a node CI K8 template.
  annotations:
    github.com/project-slug: kubeosx/kubeos-dotnet-template
    backstage.io/techdocs-ref: dir:.
  tags:
    - dotnet
    - template
  links:
    - url: https://github.com/kubeosx/kubeos-node-template
      icon: web
      title: Github
    - url: https://github.com/kubeosx/kubeos-node-template/issues
      icon: web
      title: Github Issues
spec:
  type: service
  owner: platform-engineering-team
  lifecycle: experimental
  dependsOn: ['component:kubeos', component:kubeos-cluster, component:kubeos-baseline]
  system: kubeos-idp