apiVersion: batch/v1
kind: Job
metadata:
  name: ${{values.serviceName}}
spec:
  completions: 2
  parallelism: 1
  completionMode: Indexed  # required for the feature
  backoffLimitPerIndex: 1  # maximal number of failures per index
  maxFailedIndexes: 5      # maximal number of failed indexes before terminating the Job execution
  template:
    spec:
      restartPolicy: Never # required for the feature
      containers:
      - name: ${{values.serviceName}}
        image:  ${{values.docker_username}}/${{values.serviceName}}:1